// *** WARNING: this file was generated by khulnasoft-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as khulnasoft from "@khulnasoft/khulnasoft";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface Data {
    boolArray: boolean[];
    boolean: boolean;
    float: number;
    innerData: outputs.InnerData;
    integer: number;
    string: string;
    stringMap: {[key: string]: string};
}

export interface InnerData {
    boolArray: boolean[];
    boolean: boolean;
    float: number;
    integer: number;
    string: string;
    stringMap: {[key: string]: string};
}

