// *** WARNING: this file was generated by khulnasoft-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as khulnasoft from "@khulnasoft/khulnasoft";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface DataArgs {
    boolArray: khulnasoft.Input<khulnasoft.Input<boolean>[]>;
    boolean: khulnasoft.Input<boolean>;
    float: khulnasoft.Input<number>;
    innerData: khulnasoft.Input<inputs.InnerDataArgs>;
    integer: khulnasoft.Input<number>;
    string: khulnasoft.Input<string>;
    stringMap: khulnasoft.Input<{[key: string]: khulnasoft.Input<string>}>;
}

export interface InnerDataArgs {
    boolArray: khulnasoft.Input<khulnasoft.Input<boolean>[]>;
    boolean: khulnasoft.Input<boolean>;
    float: khulnasoft.Input<number>;
    integer: khulnasoft.Input<number>;
    string: khulnasoft.Input<string>;
    stringMap: khulnasoft.Input<{[key: string]: khulnasoft.Input<string>}>;
}
