# coding=utf-8
# *** WARNING: this file was generated by khulnasoft-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import khulnasoft
import khulnasoft.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'SecretInvokeResult',
    'AwaitableSecretInvokeResult',
    'secret_invoke',
    'secret_invoke_output',
]

@khulnasoft.output_type
class SecretInvokeResult:
    def __init__(__self__, response=None, secret=None):
        if response and not isinstance(response, str):
            raise TypeError("Expected argument 'response' to be a str")
        khulnasoft.set(__self__, "response", response)
        if secret and not isinstance(secret, bool):
            raise TypeError("Expected argument 'secret' to be a bool")
        khulnasoft.set(__self__, "secret", secret)

    @property
    @khulnasoft.getter
    def response(self) -> str:
        return khulnasoft.get(self, "response")

    @property
    @khulnasoft.getter
    def secret(self) -> bool:
        return khulnasoft.get(self, "secret")


class AwaitableSecretInvokeResult(SecretInvokeResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return SecretInvokeResult(
            response=self.response,
            secret=self.secret)


def secret_invoke(secret_response: Optional[bool] = None,
                  value: Optional[str] = None,
                  opts: Optional[khulnasoft.InvokeOptions] = None) -> AwaitableSecretInvokeResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['secretResponse'] = secret_response
    __args__['value'] = value
    opts = khulnasoft.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = khulnasoft.runtime.invoke('simple-invoke:index:secretInvoke', __args__, opts=opts, typ=SecretInvokeResult).value

    return AwaitableSecretInvokeResult(
        response=khulnasoft.get(__ret__, 'response'),
        secret=khulnasoft.get(__ret__, 'secret'))
def secret_invoke_output(secret_response: Optional[khulnasoft.Input[bool]] = None,
                         value: Optional[khulnasoft.Input[str]] = None,
                         opts: Optional[Union[khulnasoft.InvokeOptions, khulnasoft.InvokeOutputOptions]] = None) -> khulnasoft.Output[SecretInvokeResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['secretResponse'] = secret_response
    __args__['value'] = value
    opts = khulnasoft.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = khulnasoft.runtime.invoke_output('simple-invoke:index:secretInvoke', __args__, opts=opts, typ=SecretInvokeResult)
    return __ret__.apply(lambda __response__: SecretInvokeResult(
        response=khulnasoft.get(__response__, 'response'),
        secret=khulnasoft.get(__response__, 'secret')))
