// Code generated by khulnasoft-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package configgrpc

import (
	"context"
	"reflect"

	"example.com/khulnasoft-config-grpc/sdk/go/configgrpc/internal"
	"github.com/khulnasoft/sdk/go/khulnasoft"
)

func ToSecret(ctx *khulnasoft.Context, args *ToSecretArgs, opts ...khulnasoft.InvokeOption) (*ToSecretResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv ToSecretResult
	err := ctx.Invoke("config-grpc:index:toSecret", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type ToSecretArgs struct {
	Bool1             *bool              `khulnasoft:"bool1"`
	Bool2             *bool              `khulnasoft:"bool2"`
	Bool3             *bool              `khulnasoft:"bool3"`
	Int1              *int               `khulnasoft:"int1"`
	Int2              *int               `khulnasoft:"int2"`
	Int3              *int               `khulnasoft:"int3"`
	ListBool1         []bool             `khulnasoft:"listBool1"`
	ListBool2         []bool             `khulnasoft:"listBool2"`
	ListBool3         []bool             `khulnasoft:"listBool3"`
	ListInt1          []int              `khulnasoft:"listInt1"`
	ListInt2          []int              `khulnasoft:"listInt2"`
	ListInt3          []int              `khulnasoft:"listInt3"`
	ListNum1          []float64          `khulnasoft:"listNum1"`
	ListNum2          []float64          `khulnasoft:"listNum2"`
	ListNum3          []float64          `khulnasoft:"listNum3"`
	ListSecretBool1   []bool             `khulnasoft:"listSecretBool1"`
	ListSecretBool2   []bool             `khulnasoft:"listSecretBool2"`
	ListSecretBool3   []bool             `khulnasoft:"listSecretBool3"`
	ListSecretInt1    []int              `khulnasoft:"listSecretInt1"`
	ListSecretInt2    []int              `khulnasoft:"listSecretInt2"`
	ListSecretInt3    []int              `khulnasoft:"listSecretInt3"`
	ListSecretNum1    []float64          `khulnasoft:"listSecretNum1"`
	ListSecretNum2    []float64          `khulnasoft:"listSecretNum2"`
	ListSecretNum3    []float64          `khulnasoft:"listSecretNum3"`
	ListSecretString1 []string           `khulnasoft:"listSecretString1"`
	ListSecretString2 []string           `khulnasoft:"listSecretString2"`
	ListSecretString3 []string           `khulnasoft:"listSecretString3"`
	ListString1       []string           `khulnasoft:"listString1"`
	ListString2       []string           `khulnasoft:"listString2"`
	ListString3       []string           `khulnasoft:"listString3"`
	MapBool1          map[string]bool    `khulnasoft:"mapBool1"`
	MapBool2          map[string]bool    `khulnasoft:"mapBool2"`
	MapBool3          map[string]bool    `khulnasoft:"mapBool3"`
	MapInt1           map[string]int     `khulnasoft:"mapInt1"`
	MapInt2           map[string]int     `khulnasoft:"mapInt2"`
	MapInt3           map[string]int     `khulnasoft:"mapInt3"`
	MapNum1           map[string]float64 `khulnasoft:"mapNum1"`
	MapNum2           map[string]float64 `khulnasoft:"mapNum2"`
	MapNum3           map[string]float64 `khulnasoft:"mapNum3"`
	MapSecretBool1    map[string]bool    `khulnasoft:"mapSecretBool1"`
	MapSecretBool2    map[string]bool    `khulnasoft:"mapSecretBool2"`
	MapSecretBool3    map[string]bool    `khulnasoft:"mapSecretBool3"`
	MapSecretInt1     map[string]int     `khulnasoft:"mapSecretInt1"`
	MapSecretInt2     map[string]int     `khulnasoft:"mapSecretInt2"`
	MapSecretInt3     map[string]int     `khulnasoft:"mapSecretInt3"`
	MapSecretNum1     map[string]float64 `khulnasoft:"mapSecretNum1"`
	MapSecretNum2     map[string]float64 `khulnasoft:"mapSecretNum2"`
	MapSecretNum3     map[string]float64 `khulnasoft:"mapSecretNum3"`
	MapSecretString1  map[string]string  `khulnasoft:"mapSecretString1"`
	MapSecretString2  map[string]string  `khulnasoft:"mapSecretString2"`
	MapSecretString3  map[string]string  `khulnasoft:"mapSecretString3"`
	MapString1        map[string]string  `khulnasoft:"mapString1"`
	MapString2        map[string]string  `khulnasoft:"mapString2"`
	MapString3        map[string]string  `khulnasoft:"mapString3"`
	Num1              *float64           `khulnasoft:"num1"`
	Num2              *float64           `khulnasoft:"num2"`
	Num3              *float64           `khulnasoft:"num3"`
	ObjBool1          *Tbool1            `khulnasoft:"objBool1"`
	ObjBool2          *Tbool2            `khulnasoft:"objBool2"`
	ObjBool3          *Tbool3            `khulnasoft:"objBool3"`
	ObjInt1           *Tint1             `khulnasoft:"objInt1"`
	ObjInt2           *Tint2             `khulnasoft:"objInt2"`
	ObjInt3           *Tint3             `khulnasoft:"objInt3"`
	ObjNum1           *Tnum1             `khulnasoft:"objNum1"`
	ObjNum2           *Tnum2             `khulnasoft:"objNum2"`
	ObjNum3           *Tnum3             `khulnasoft:"objNum3"`
	ObjSecretBool1    *TsecretBool1      `khulnasoft:"objSecretBool1"`
	ObjSecretBool2    *TsecretBool2      `khulnasoft:"objSecretBool2"`
	ObjSecretBool3    *TsecretBool3      `khulnasoft:"objSecretBool3"`
	ObjSecretInt1     *TsecretInt1       `khulnasoft:"objSecretInt1"`
	ObjSecretInt2     *TsecretInt2       `khulnasoft:"objSecretInt2"`
	ObjSecretInt3     *TsecretInt3       `khulnasoft:"objSecretInt3"`
	ObjSecretNum1     *TsecretNum1       `khulnasoft:"objSecretNum1"`
	ObjSecretNum2     *TsecretNum2       `khulnasoft:"objSecretNum2"`
	ObjSecretNum3     *TsecretNum3       `khulnasoft:"objSecretNum3"`
	ObjSecretString1  *TsecretString1    `khulnasoft:"objSecretString1"`
	ObjSecretString2  *TsecretString2    `khulnasoft:"objSecretString2"`
	ObjSecretString3  *TsecretString3    `khulnasoft:"objSecretString3"`
	ObjString1        *Tstring1          `khulnasoft:"objString1"`
	ObjString2        *Tstring2          `khulnasoft:"objString2"`
	ObjString3        *Tstring3          `khulnasoft:"objString3"`
	SecretBool1       *bool              `khulnasoft:"secretBool1"`
	SecretBool2       *bool              `khulnasoft:"secretBool2"`
	SecretBool3       *bool              `khulnasoft:"secretBool3"`
	SecretInt1        *int               `khulnasoft:"secretInt1"`
	SecretInt2        *int               `khulnasoft:"secretInt2"`
	SecretInt3        *int               `khulnasoft:"secretInt3"`
	SecretNum1        *float64           `khulnasoft:"secretNum1"`
	SecretNum2        *float64           `khulnasoft:"secretNum2"`
	SecretNum3        *float64           `khulnasoft:"secretNum3"`
	SecretString1     *string            `khulnasoft:"secretString1"`
	SecretString2     *string            `khulnasoft:"secretString2"`
	SecretString3     *string            `khulnasoft:"secretString3"`
	String1           *string            `khulnasoft:"string1"`
	String2           *string            `khulnasoft:"string2"`
	String3           *string            `khulnasoft:"string3"`
}

type ToSecretResult struct {
	Bool1             bool               `khulnasoft:"bool1"`
	Bool2             bool               `khulnasoft:"bool2"`
	Bool3             bool               `khulnasoft:"bool3"`
	Int1              int                `khulnasoft:"int1"`
	Int2              int                `khulnasoft:"int2"`
	Int3              int                `khulnasoft:"int3"`
	ListBool1         []bool             `khulnasoft:"listBool1"`
	ListBool2         []bool             `khulnasoft:"listBool2"`
	ListBool3         []bool             `khulnasoft:"listBool3"`
	ListInt1          []int              `khulnasoft:"listInt1"`
	ListInt2          []int              `khulnasoft:"listInt2"`
	ListInt3          []int              `khulnasoft:"listInt3"`
	ListNum1          []float64          `khulnasoft:"listNum1"`
	ListNum2          []float64          `khulnasoft:"listNum2"`
	ListNum3          []float64          `khulnasoft:"listNum3"`
	ListSecretBool1   []bool             `khulnasoft:"listSecretBool1"`
	ListSecretBool2   []bool             `khulnasoft:"listSecretBool2"`
	ListSecretBool3   []bool             `khulnasoft:"listSecretBool3"`
	ListSecretInt1    []int              `khulnasoft:"listSecretInt1"`
	ListSecretInt2    []int              `khulnasoft:"listSecretInt2"`
	ListSecretInt3    []int              `khulnasoft:"listSecretInt3"`
	ListSecretNum1    []float64          `khulnasoft:"listSecretNum1"`
	ListSecretNum2    []float64          `khulnasoft:"listSecretNum2"`
	ListSecretNum3    []float64          `khulnasoft:"listSecretNum3"`
	ListSecretString1 []string           `khulnasoft:"listSecretString1"`
	ListSecretString2 []string           `khulnasoft:"listSecretString2"`
	ListSecretString3 []string           `khulnasoft:"listSecretString3"`
	ListString1       []string           `khulnasoft:"listString1"`
	ListString2       []string           `khulnasoft:"listString2"`
	ListString3       []string           `khulnasoft:"listString3"`
	MapBool1          map[string]bool    `khulnasoft:"mapBool1"`
	MapBool2          map[string]bool    `khulnasoft:"mapBool2"`
	MapBool3          map[string]bool    `khulnasoft:"mapBool3"`
	MapInt1           map[string]int     `khulnasoft:"mapInt1"`
	MapInt2           map[string]int     `khulnasoft:"mapInt2"`
	MapInt3           map[string]int     `khulnasoft:"mapInt3"`
	MapNum1           map[string]float64 `khulnasoft:"mapNum1"`
	MapNum2           map[string]float64 `khulnasoft:"mapNum2"`
	MapNum3           map[string]float64 `khulnasoft:"mapNum3"`
	MapSecretBool1    map[string]bool    `khulnasoft:"mapSecretBool1"`
	MapSecretBool2    map[string]bool    `khulnasoft:"mapSecretBool2"`
	MapSecretBool3    map[string]bool    `khulnasoft:"mapSecretBool3"`
	MapSecretInt1     map[string]int     `khulnasoft:"mapSecretInt1"`
	MapSecretInt2     map[string]int     `khulnasoft:"mapSecretInt2"`
	MapSecretInt3     map[string]int     `khulnasoft:"mapSecretInt3"`
	MapSecretNum1     map[string]float64 `khulnasoft:"mapSecretNum1"`
	MapSecretNum2     map[string]float64 `khulnasoft:"mapSecretNum2"`
	MapSecretNum3     map[string]float64 `khulnasoft:"mapSecretNum3"`
	MapSecretString1  map[string]string  `khulnasoft:"mapSecretString1"`
	MapSecretString2  map[string]string  `khulnasoft:"mapSecretString2"`
	MapSecretString3  map[string]string  `khulnasoft:"mapSecretString3"`
	MapString1        map[string]string  `khulnasoft:"mapString1"`
	MapString2        map[string]string  `khulnasoft:"mapString2"`
	MapString3        map[string]string  `khulnasoft:"mapString3"`
	Num1              float64            `khulnasoft:"num1"`
	Num2              float64            `khulnasoft:"num2"`
	Num3              float64            `khulnasoft:"num3"`
	ObjBool1          Tbool1             `khulnasoft:"objBool1"`
	ObjBool2          Tbool2             `khulnasoft:"objBool2"`
	ObjBool3          Tbool3             `khulnasoft:"objBool3"`
	ObjInt1           Tint1              `khulnasoft:"objInt1"`
	ObjInt2           Tint2              `khulnasoft:"objInt2"`
	ObjInt3           Tint3              `khulnasoft:"objInt3"`
	ObjNum1           Tnum1              `khulnasoft:"objNum1"`
	ObjNum2           Tnum2              `khulnasoft:"objNum2"`
	ObjNum3           Tnum3              `khulnasoft:"objNum3"`
	ObjSecretBool1    TsecretBool1       `khulnasoft:"objSecretBool1"`
	ObjSecretBool2    TsecretBool2       `khulnasoft:"objSecretBool2"`
	ObjSecretBool3    TsecretBool3       `khulnasoft:"objSecretBool3"`
	ObjSecretInt1     TsecretInt1        `khulnasoft:"objSecretInt1"`
	ObjSecretInt2     TsecretInt2        `khulnasoft:"objSecretInt2"`
	ObjSecretInt3     TsecretInt3        `khulnasoft:"objSecretInt3"`
	ObjSecretNum1     TsecretNum1        `khulnasoft:"objSecretNum1"`
	ObjSecretNum2     TsecretNum2        `khulnasoft:"objSecretNum2"`
	ObjSecretNum3     TsecretNum3        `khulnasoft:"objSecretNum3"`
	ObjSecretString1  TsecretString1     `khulnasoft:"objSecretString1"`
	ObjSecretString2  TsecretString2     `khulnasoft:"objSecretString2"`
	ObjSecretString3  TsecretString3     `khulnasoft:"objSecretString3"`
	ObjString1        Tstring1           `khulnasoft:"objString1"`
	ObjString2        Tstring2           `khulnasoft:"objString2"`
	ObjString3        Tstring3           `khulnasoft:"objString3"`
	SecretBool1       bool               `khulnasoft:"secretBool1"`
	SecretBool2       bool               `khulnasoft:"secretBool2"`
	SecretBool3       bool               `khulnasoft:"secretBool3"`
	SecretInt1        int                `khulnasoft:"secretInt1"`
	SecretInt2        int                `khulnasoft:"secretInt2"`
	SecretInt3        int                `khulnasoft:"secretInt3"`
	SecretNum1        float64            `khulnasoft:"secretNum1"`
	SecretNum2        float64            `khulnasoft:"secretNum2"`
	SecretNum3        float64            `khulnasoft:"secretNum3"`
	SecretString1     string             `khulnasoft:"secretString1"`
	SecretString2     string             `khulnasoft:"secretString2"`
	SecretString3     string             `khulnasoft:"secretString3"`
	String1           string             `khulnasoft:"string1"`
	String2           string             `khulnasoft:"string2"`
	String3           string             `khulnasoft:"string3"`
}

func ToSecretOutput(ctx *khulnasoft.Context, args ToSecretOutputArgs, opts ...khulnasoft.InvokeOption) ToSecretResultOutput {
	return khulnasoft.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (ToSecretResultOutput, error) {
			args := v.(ToSecretArgs)
			options := khulnasoft.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("config-grpc:index:toSecret", args, ToSecretResultOutput{}, options).(ToSecretResultOutput), nil
		}).(ToSecretResultOutput)
}

type ToSecretOutputArgs struct {
	Bool1             khulnasoft.BoolPtrInput      `khulnasoft:"bool1"`
	Bool2             khulnasoft.BoolPtrInput      `khulnasoft:"bool2"`
	Bool3             khulnasoft.BoolPtrInput      `khulnasoft:"bool3"`
	Int1              khulnasoft.IntPtrInput       `khulnasoft:"int1"`
	Int2              khulnasoft.IntPtrInput       `khulnasoft:"int2"`
	Int3              khulnasoft.IntPtrInput       `khulnasoft:"int3"`
	ListBool1         khulnasoft.BoolArrayInput    `khulnasoft:"listBool1"`
	ListBool2         khulnasoft.BoolArrayInput    `khulnasoft:"listBool2"`
	ListBool3         khulnasoft.BoolArrayInput    `khulnasoft:"listBool3"`
	ListInt1          khulnasoft.IntArrayInput     `khulnasoft:"listInt1"`
	ListInt2          khulnasoft.IntArrayInput     `khulnasoft:"listInt2"`
	ListInt3          khulnasoft.IntArrayInput     `khulnasoft:"listInt3"`
	ListNum1          khulnasoft.Float64ArrayInput `khulnasoft:"listNum1"`
	ListNum2          khulnasoft.Float64ArrayInput `khulnasoft:"listNum2"`
	ListNum3          khulnasoft.Float64ArrayInput `khulnasoft:"listNum3"`
	ListSecretBool1   khulnasoft.BoolArrayInput    `khulnasoft:"listSecretBool1"`
	ListSecretBool2   khulnasoft.BoolArrayInput    `khulnasoft:"listSecretBool2"`
	ListSecretBool3   khulnasoft.BoolArrayInput    `khulnasoft:"listSecretBool3"`
	ListSecretInt1    khulnasoft.IntArrayInput     `khulnasoft:"listSecretInt1"`
	ListSecretInt2    khulnasoft.IntArrayInput     `khulnasoft:"listSecretInt2"`
	ListSecretInt3    khulnasoft.IntArrayInput     `khulnasoft:"listSecretInt3"`
	ListSecretNum1    khulnasoft.Float64ArrayInput `khulnasoft:"listSecretNum1"`
	ListSecretNum2    khulnasoft.Float64ArrayInput `khulnasoft:"listSecretNum2"`
	ListSecretNum3    khulnasoft.Float64ArrayInput `khulnasoft:"listSecretNum3"`
	ListSecretString1 khulnasoft.StringArrayInput  `khulnasoft:"listSecretString1"`
	ListSecretString2 khulnasoft.StringArrayInput  `khulnasoft:"listSecretString2"`
	ListSecretString3 khulnasoft.StringArrayInput  `khulnasoft:"listSecretString3"`
	ListString1       khulnasoft.StringArrayInput  `khulnasoft:"listString1"`
	ListString2       khulnasoft.StringArrayInput  `khulnasoft:"listString2"`
	ListString3       khulnasoft.StringArrayInput  `khulnasoft:"listString3"`
	MapBool1          khulnasoft.BoolMapInput      `khulnasoft:"mapBool1"`
	MapBool2          khulnasoft.BoolMapInput      `khulnasoft:"mapBool2"`
	MapBool3          khulnasoft.BoolMapInput      `khulnasoft:"mapBool3"`
	MapInt1           khulnasoft.IntMapInput       `khulnasoft:"mapInt1"`
	MapInt2           khulnasoft.IntMapInput       `khulnasoft:"mapInt2"`
	MapInt3           khulnasoft.IntMapInput       `khulnasoft:"mapInt3"`
	MapNum1           khulnasoft.Float64MapInput   `khulnasoft:"mapNum1"`
	MapNum2           khulnasoft.Float64MapInput   `khulnasoft:"mapNum2"`
	MapNum3           khulnasoft.Float64MapInput   `khulnasoft:"mapNum3"`
	MapSecretBool1    khulnasoft.BoolMapInput      `khulnasoft:"mapSecretBool1"`
	MapSecretBool2    khulnasoft.BoolMapInput      `khulnasoft:"mapSecretBool2"`
	MapSecretBool3    khulnasoft.BoolMapInput      `khulnasoft:"mapSecretBool3"`
	MapSecretInt1     khulnasoft.IntMapInput       `khulnasoft:"mapSecretInt1"`
	MapSecretInt2     khulnasoft.IntMapInput       `khulnasoft:"mapSecretInt2"`
	MapSecretInt3     khulnasoft.IntMapInput       `khulnasoft:"mapSecretInt3"`
	MapSecretNum1     khulnasoft.Float64MapInput   `khulnasoft:"mapSecretNum1"`
	MapSecretNum2     khulnasoft.Float64MapInput   `khulnasoft:"mapSecretNum2"`
	MapSecretNum3     khulnasoft.Float64MapInput   `khulnasoft:"mapSecretNum3"`
	MapSecretString1  khulnasoft.StringMapInput    `khulnasoft:"mapSecretString1"`
	MapSecretString2  khulnasoft.StringMapInput    `khulnasoft:"mapSecretString2"`
	MapSecretString3  khulnasoft.StringMapInput    `khulnasoft:"mapSecretString3"`
	MapString1        khulnasoft.StringMapInput    `khulnasoft:"mapString1"`
	MapString2        khulnasoft.StringMapInput    `khulnasoft:"mapString2"`
	MapString3        khulnasoft.StringMapInput    `khulnasoft:"mapString3"`
	Num1              khulnasoft.Float64PtrInput   `khulnasoft:"num1"`
	Num2              khulnasoft.Float64PtrInput   `khulnasoft:"num2"`
	Num3              khulnasoft.Float64PtrInput   `khulnasoft:"num3"`
	ObjBool1          Tbool1PtrInput           `khulnasoft:"objBool1"`
	ObjBool2          Tbool2PtrInput           `khulnasoft:"objBool2"`
	ObjBool3          Tbool3PtrInput           `khulnasoft:"objBool3"`
	ObjInt1           Tint1PtrInput            `khulnasoft:"objInt1"`
	ObjInt2           Tint2PtrInput            `khulnasoft:"objInt2"`
	ObjInt3           Tint3PtrInput            `khulnasoft:"objInt3"`
	ObjNum1           Tnum1PtrInput            `khulnasoft:"objNum1"`
	ObjNum2           Tnum2PtrInput            `khulnasoft:"objNum2"`
	ObjNum3           Tnum3PtrInput            `khulnasoft:"objNum3"`
	ObjSecretBool1    TsecretBool1PtrInput     `khulnasoft:"objSecretBool1"`
	ObjSecretBool2    TsecretBool2PtrInput     `khulnasoft:"objSecretBool2"`
	ObjSecretBool3    TsecretBool3PtrInput     `khulnasoft:"objSecretBool3"`
	ObjSecretInt1     TsecretInt1PtrInput      `khulnasoft:"objSecretInt1"`
	ObjSecretInt2     TsecretInt2PtrInput      `khulnasoft:"objSecretInt2"`
	ObjSecretInt3     TsecretInt3PtrInput      `khulnasoft:"objSecretInt3"`
	ObjSecretNum1     TsecretNum1PtrInput      `khulnasoft:"objSecretNum1"`
	ObjSecretNum2     TsecretNum2PtrInput      `khulnasoft:"objSecretNum2"`
	ObjSecretNum3     TsecretNum3PtrInput      `khulnasoft:"objSecretNum3"`
	ObjSecretString1  TsecretString1PtrInput   `khulnasoft:"objSecretString1"`
	ObjSecretString2  TsecretString2PtrInput   `khulnasoft:"objSecretString2"`
	ObjSecretString3  TsecretString3PtrInput   `khulnasoft:"objSecretString3"`
	ObjString1        Tstring1PtrInput         `khulnasoft:"objString1"`
	ObjString2        Tstring2PtrInput         `khulnasoft:"objString2"`
	ObjString3        Tstring3PtrInput         `khulnasoft:"objString3"`
	SecretBool1       khulnasoft.BoolPtrInput      `khulnasoft:"secretBool1"`
	SecretBool2       khulnasoft.BoolPtrInput      `khulnasoft:"secretBool2"`
	SecretBool3       khulnasoft.BoolPtrInput      `khulnasoft:"secretBool3"`
	SecretInt1        khulnasoft.IntPtrInput       `khulnasoft:"secretInt1"`
	SecretInt2        khulnasoft.IntPtrInput       `khulnasoft:"secretInt2"`
	SecretInt3        khulnasoft.IntPtrInput       `khulnasoft:"secretInt3"`
	SecretNum1        khulnasoft.Float64PtrInput   `khulnasoft:"secretNum1"`
	SecretNum2        khulnasoft.Float64PtrInput   `khulnasoft:"secretNum2"`
	SecretNum3        khulnasoft.Float64PtrInput   `khulnasoft:"secretNum3"`
	SecretString1     khulnasoft.StringPtrInput    `khulnasoft:"secretString1"`
	SecretString2     khulnasoft.StringPtrInput    `khulnasoft:"secretString2"`
	SecretString3     khulnasoft.StringPtrInput    `khulnasoft:"secretString3"`
	String1           khulnasoft.StringPtrInput    `khulnasoft:"string1"`
	String2           khulnasoft.StringPtrInput    `khulnasoft:"string2"`
	String3           khulnasoft.StringPtrInput    `khulnasoft:"string3"`
}

func (ToSecretOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ToSecretArgs)(nil)).Elem()
}

type ToSecretResultOutput struct{ *khulnasoft.OutputState }

func (ToSecretResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ToSecretResult)(nil)).Elem()
}

func (o ToSecretResultOutput) ToToSecretResultOutput() ToSecretResultOutput {
	return o
}

func (o ToSecretResultOutput) ToToSecretResultOutputWithContext(ctx context.Context) ToSecretResultOutput {
	return o
}

func (o ToSecretResultOutput) Bool1() khulnasoft.BoolOutput {
	return o.ApplyT(func(v ToSecretResult) bool { return v.Bool1 }).(khulnasoft.BoolOutput)
}

func (o ToSecretResultOutput) Bool2() khulnasoft.BoolOutput {
	return o.ApplyT(func(v ToSecretResult) bool { return v.Bool2 }).(khulnasoft.BoolOutput)
}

func (o ToSecretResultOutput) Bool3() khulnasoft.BoolOutput {
	return o.ApplyT(func(v ToSecretResult) bool { return v.Bool3 }).(khulnasoft.BoolOutput)
}

func (o ToSecretResultOutput) Int1() khulnasoft.IntOutput {
	return o.ApplyT(func(v ToSecretResult) int { return v.Int1 }).(khulnasoft.IntOutput)
}

func (o ToSecretResultOutput) Int2() khulnasoft.IntOutput {
	return o.ApplyT(func(v ToSecretResult) int { return v.Int2 }).(khulnasoft.IntOutput)
}

func (o ToSecretResultOutput) Int3() khulnasoft.IntOutput {
	return o.ApplyT(func(v ToSecretResult) int { return v.Int3 }).(khulnasoft.IntOutput)
}

func (o ToSecretResultOutput) ListBool1() khulnasoft.BoolArrayOutput {
	return o.ApplyT(func(v ToSecretResult) []bool { return v.ListBool1 }).(khulnasoft.BoolArrayOutput)
}

func (o ToSecretResultOutput) ListBool2() khulnasoft.BoolArrayOutput {
	return o.ApplyT(func(v ToSecretResult) []bool { return v.ListBool2 }).(khulnasoft.BoolArrayOutput)
}

func (o ToSecretResultOutput) ListBool3() khulnasoft.BoolArrayOutput {
	return o.ApplyT(func(v ToSecretResult) []bool { return v.ListBool3 }).(khulnasoft.BoolArrayOutput)
}

func (o ToSecretResultOutput) ListInt1() khulnasoft.IntArrayOutput {
	return o.ApplyT(func(v ToSecretResult) []int { return v.ListInt1 }).(khulnasoft.IntArrayOutput)
}

func (o ToSecretResultOutput) ListInt2() khulnasoft.IntArrayOutput {
	return o.ApplyT(func(v ToSecretResult) []int { return v.ListInt2 }).(khulnasoft.IntArrayOutput)
}

func (o ToSecretResultOutput) ListInt3() khulnasoft.IntArrayOutput {
	return o.ApplyT(func(v ToSecretResult) []int { return v.ListInt3 }).(khulnasoft.IntArrayOutput)
}

func (o ToSecretResultOutput) ListNum1() khulnasoft.Float64ArrayOutput {
	return o.ApplyT(func(v ToSecretResult) []float64 { return v.ListNum1 }).(khulnasoft.Float64ArrayOutput)
}

func (o ToSecretResultOutput) ListNum2() khulnasoft.Float64ArrayOutput {
	return o.ApplyT(func(v ToSecretResult) []float64 { return v.ListNum2 }).(khulnasoft.Float64ArrayOutput)
}

func (o ToSecretResultOutput) ListNum3() khulnasoft.Float64ArrayOutput {
	return o.ApplyT(func(v ToSecretResult) []float64 { return v.ListNum3 }).(khulnasoft.Float64ArrayOutput)
}

func (o ToSecretResultOutput) ListSecretBool1() khulnasoft.BoolArrayOutput {
	return o.ApplyT(func(v ToSecretResult) []bool { return v.ListSecretBool1 }).(khulnasoft.BoolArrayOutput)
}

func (o ToSecretResultOutput) ListSecretBool2() khulnasoft.BoolArrayOutput {
	return o.ApplyT(func(v ToSecretResult) []bool { return v.ListSecretBool2 }).(khulnasoft.BoolArrayOutput)
}

func (o ToSecretResultOutput) ListSecretBool3() khulnasoft.BoolArrayOutput {
	return o.ApplyT(func(v ToSecretResult) []bool { return v.ListSecretBool3 }).(khulnasoft.BoolArrayOutput)
}

func (o ToSecretResultOutput) ListSecretInt1() khulnasoft.IntArrayOutput {
	return o.ApplyT(func(v ToSecretResult) []int { return v.ListSecretInt1 }).(khulnasoft.IntArrayOutput)
}

func (o ToSecretResultOutput) ListSecretInt2() khulnasoft.IntArrayOutput {
	return o.ApplyT(func(v ToSecretResult) []int { return v.ListSecretInt2 }).(khulnasoft.IntArrayOutput)
}

func (o ToSecretResultOutput) ListSecretInt3() khulnasoft.IntArrayOutput {
	return o.ApplyT(func(v ToSecretResult) []int { return v.ListSecretInt3 }).(khulnasoft.IntArrayOutput)
}

func (o ToSecretResultOutput) ListSecretNum1() khulnasoft.Float64ArrayOutput {
	return o.ApplyT(func(v ToSecretResult) []float64 { return v.ListSecretNum1 }).(khulnasoft.Float64ArrayOutput)
}

func (o ToSecretResultOutput) ListSecretNum2() khulnasoft.Float64ArrayOutput {
	return o.ApplyT(func(v ToSecretResult) []float64 { return v.ListSecretNum2 }).(khulnasoft.Float64ArrayOutput)
}

func (o ToSecretResultOutput) ListSecretNum3() khulnasoft.Float64ArrayOutput {
	return o.ApplyT(func(v ToSecretResult) []float64 { return v.ListSecretNum3 }).(khulnasoft.Float64ArrayOutput)
}

func (o ToSecretResultOutput) ListSecretString1() khulnasoft.StringArrayOutput {
	return o.ApplyT(func(v ToSecretResult) []string { return v.ListSecretString1 }).(khulnasoft.StringArrayOutput)
}

func (o ToSecretResultOutput) ListSecretString2() khulnasoft.StringArrayOutput {
	return o.ApplyT(func(v ToSecretResult) []string { return v.ListSecretString2 }).(khulnasoft.StringArrayOutput)
}

func (o ToSecretResultOutput) ListSecretString3() khulnasoft.StringArrayOutput {
	return o.ApplyT(func(v ToSecretResult) []string { return v.ListSecretString3 }).(khulnasoft.StringArrayOutput)
}

func (o ToSecretResultOutput) ListString1() khulnasoft.StringArrayOutput {
	return o.ApplyT(func(v ToSecretResult) []string { return v.ListString1 }).(khulnasoft.StringArrayOutput)
}

func (o ToSecretResultOutput) ListString2() khulnasoft.StringArrayOutput {
	return o.ApplyT(func(v ToSecretResult) []string { return v.ListString2 }).(khulnasoft.StringArrayOutput)
}

func (o ToSecretResultOutput) ListString3() khulnasoft.StringArrayOutput {
	return o.ApplyT(func(v ToSecretResult) []string { return v.ListString3 }).(khulnasoft.StringArrayOutput)
}

func (o ToSecretResultOutput) MapBool1() khulnasoft.BoolMapOutput {
	return o.ApplyT(func(v ToSecretResult) map[string]bool { return v.MapBool1 }).(khulnasoft.BoolMapOutput)
}

func (o ToSecretResultOutput) MapBool2() khulnasoft.BoolMapOutput {
	return o.ApplyT(func(v ToSecretResult) map[string]bool { return v.MapBool2 }).(khulnasoft.BoolMapOutput)
}

func (o ToSecretResultOutput) MapBool3() khulnasoft.BoolMapOutput {
	return o.ApplyT(func(v ToSecretResult) map[string]bool { return v.MapBool3 }).(khulnasoft.BoolMapOutput)
}

func (o ToSecretResultOutput) MapInt1() khulnasoft.IntMapOutput {
	return o.ApplyT(func(v ToSecretResult) map[string]int { return v.MapInt1 }).(khulnasoft.IntMapOutput)
}

func (o ToSecretResultOutput) MapInt2() khulnasoft.IntMapOutput {
	return o.ApplyT(func(v ToSecretResult) map[string]int { return v.MapInt2 }).(khulnasoft.IntMapOutput)
}

func (o ToSecretResultOutput) MapInt3() khulnasoft.IntMapOutput {
	return o.ApplyT(func(v ToSecretResult) map[string]int { return v.MapInt3 }).(khulnasoft.IntMapOutput)
}

func (o ToSecretResultOutput) MapNum1() khulnasoft.Float64MapOutput {
	return o.ApplyT(func(v ToSecretResult) map[string]float64 { return v.MapNum1 }).(khulnasoft.Float64MapOutput)
}

func (o ToSecretResultOutput) MapNum2() khulnasoft.Float64MapOutput {
	return o.ApplyT(func(v ToSecretResult) map[string]float64 { return v.MapNum2 }).(khulnasoft.Float64MapOutput)
}

func (o ToSecretResultOutput) MapNum3() khulnasoft.Float64MapOutput {
	return o.ApplyT(func(v ToSecretResult) map[string]float64 { return v.MapNum3 }).(khulnasoft.Float64MapOutput)
}

func (o ToSecretResultOutput) MapSecretBool1() khulnasoft.BoolMapOutput {
	return o.ApplyT(func(v ToSecretResult) map[string]bool { return v.MapSecretBool1 }).(khulnasoft.BoolMapOutput)
}

func (o ToSecretResultOutput) MapSecretBool2() khulnasoft.BoolMapOutput {
	return o.ApplyT(func(v ToSecretResult) map[string]bool { return v.MapSecretBool2 }).(khulnasoft.BoolMapOutput)
}

func (o ToSecretResultOutput) MapSecretBool3() khulnasoft.BoolMapOutput {
	return o.ApplyT(func(v ToSecretResult) map[string]bool { return v.MapSecretBool3 }).(khulnasoft.BoolMapOutput)
}

func (o ToSecretResultOutput) MapSecretInt1() khulnasoft.IntMapOutput {
	return o.ApplyT(func(v ToSecretResult) map[string]int { return v.MapSecretInt1 }).(khulnasoft.IntMapOutput)
}

func (o ToSecretResultOutput) MapSecretInt2() khulnasoft.IntMapOutput {
	return o.ApplyT(func(v ToSecretResult) map[string]int { return v.MapSecretInt2 }).(khulnasoft.IntMapOutput)
}

func (o ToSecretResultOutput) MapSecretInt3() khulnasoft.IntMapOutput {
	return o.ApplyT(func(v ToSecretResult) map[string]int { return v.MapSecretInt3 }).(khulnasoft.IntMapOutput)
}

func (o ToSecretResultOutput) MapSecretNum1() khulnasoft.Float64MapOutput {
	return o.ApplyT(func(v ToSecretResult) map[string]float64 { return v.MapSecretNum1 }).(khulnasoft.Float64MapOutput)
}

func (o ToSecretResultOutput) MapSecretNum2() khulnasoft.Float64MapOutput {
	return o.ApplyT(func(v ToSecretResult) map[string]float64 { return v.MapSecretNum2 }).(khulnasoft.Float64MapOutput)
}

func (o ToSecretResultOutput) MapSecretNum3() khulnasoft.Float64MapOutput {
	return o.ApplyT(func(v ToSecretResult) map[string]float64 { return v.MapSecretNum3 }).(khulnasoft.Float64MapOutput)
}

func (o ToSecretResultOutput) MapSecretString1() khulnasoft.StringMapOutput {
	return o.ApplyT(func(v ToSecretResult) map[string]string { return v.MapSecretString1 }).(khulnasoft.StringMapOutput)
}

func (o ToSecretResultOutput) MapSecretString2() khulnasoft.StringMapOutput {
	return o.ApplyT(func(v ToSecretResult) map[string]string { return v.MapSecretString2 }).(khulnasoft.StringMapOutput)
}

func (o ToSecretResultOutput) MapSecretString3() khulnasoft.StringMapOutput {
	return o.ApplyT(func(v ToSecretResult) map[string]string { return v.MapSecretString3 }).(khulnasoft.StringMapOutput)
}

func (o ToSecretResultOutput) MapString1() khulnasoft.StringMapOutput {
	return o.ApplyT(func(v ToSecretResult) map[string]string { return v.MapString1 }).(khulnasoft.StringMapOutput)
}

func (o ToSecretResultOutput) MapString2() khulnasoft.StringMapOutput {
	return o.ApplyT(func(v ToSecretResult) map[string]string { return v.MapString2 }).(khulnasoft.StringMapOutput)
}

func (o ToSecretResultOutput) MapString3() khulnasoft.StringMapOutput {
	return o.ApplyT(func(v ToSecretResult) map[string]string { return v.MapString3 }).(khulnasoft.StringMapOutput)
}

func (o ToSecretResultOutput) Num1() khulnasoft.Float64Output {
	return o.ApplyT(func(v ToSecretResult) float64 { return v.Num1 }).(khulnasoft.Float64Output)
}

func (o ToSecretResultOutput) Num2() khulnasoft.Float64Output {
	return o.ApplyT(func(v ToSecretResult) float64 { return v.Num2 }).(khulnasoft.Float64Output)
}

func (o ToSecretResultOutput) Num3() khulnasoft.Float64Output {
	return o.ApplyT(func(v ToSecretResult) float64 { return v.Num3 }).(khulnasoft.Float64Output)
}

func (o ToSecretResultOutput) ObjBool1() Tbool1Output {
	return o.ApplyT(func(v ToSecretResult) Tbool1 { return v.ObjBool1 }).(Tbool1Output)
}

func (o ToSecretResultOutput) ObjBool2() Tbool2Output {
	return o.ApplyT(func(v ToSecretResult) Tbool2 { return v.ObjBool2 }).(Tbool2Output)
}

func (o ToSecretResultOutput) ObjBool3() Tbool3Output {
	return o.ApplyT(func(v ToSecretResult) Tbool3 { return v.ObjBool3 }).(Tbool3Output)
}

func (o ToSecretResultOutput) ObjInt1() Tint1Output {
	return o.ApplyT(func(v ToSecretResult) Tint1 { return v.ObjInt1 }).(Tint1Output)
}

func (o ToSecretResultOutput) ObjInt2() Tint2Output {
	return o.ApplyT(func(v ToSecretResult) Tint2 { return v.ObjInt2 }).(Tint2Output)
}

func (o ToSecretResultOutput) ObjInt3() Tint3Output {
	return o.ApplyT(func(v ToSecretResult) Tint3 { return v.ObjInt3 }).(Tint3Output)
}

func (o ToSecretResultOutput) ObjNum1() Tnum1Output {
	return o.ApplyT(func(v ToSecretResult) Tnum1 { return v.ObjNum1 }).(Tnum1Output)
}

func (o ToSecretResultOutput) ObjNum2() Tnum2Output {
	return o.ApplyT(func(v ToSecretResult) Tnum2 { return v.ObjNum2 }).(Tnum2Output)
}

func (o ToSecretResultOutput) ObjNum3() Tnum3Output {
	return o.ApplyT(func(v ToSecretResult) Tnum3 { return v.ObjNum3 }).(Tnum3Output)
}

func (o ToSecretResultOutput) ObjSecretBool1() TsecretBool1Output {
	return o.ApplyT(func(v ToSecretResult) TsecretBool1 { return v.ObjSecretBool1 }).(TsecretBool1Output)
}

func (o ToSecretResultOutput) ObjSecretBool2() TsecretBool2Output {
	return o.ApplyT(func(v ToSecretResult) TsecretBool2 { return v.ObjSecretBool2 }).(TsecretBool2Output)
}

func (o ToSecretResultOutput) ObjSecretBool3() TsecretBool3Output {
	return o.ApplyT(func(v ToSecretResult) TsecretBool3 { return v.ObjSecretBool3 }).(TsecretBool3Output)
}

func (o ToSecretResultOutput) ObjSecretInt1() TsecretInt1Output {
	return o.ApplyT(func(v ToSecretResult) TsecretInt1 { return v.ObjSecretInt1 }).(TsecretInt1Output)
}

func (o ToSecretResultOutput) ObjSecretInt2() TsecretInt2Output {
	return o.ApplyT(func(v ToSecretResult) TsecretInt2 { return v.ObjSecretInt2 }).(TsecretInt2Output)
}

func (o ToSecretResultOutput) ObjSecretInt3() TsecretInt3Output {
	return o.ApplyT(func(v ToSecretResult) TsecretInt3 { return v.ObjSecretInt3 }).(TsecretInt3Output)
}

func (o ToSecretResultOutput) ObjSecretNum1() TsecretNum1Output {
	return o.ApplyT(func(v ToSecretResult) TsecretNum1 { return v.ObjSecretNum1 }).(TsecretNum1Output)
}

func (o ToSecretResultOutput) ObjSecretNum2() TsecretNum2Output {
	return o.ApplyT(func(v ToSecretResult) TsecretNum2 { return v.ObjSecretNum2 }).(TsecretNum2Output)
}

func (o ToSecretResultOutput) ObjSecretNum3() TsecretNum3Output {
	return o.ApplyT(func(v ToSecretResult) TsecretNum3 { return v.ObjSecretNum3 }).(TsecretNum3Output)
}

func (o ToSecretResultOutput) ObjSecretString1() TsecretString1Output {
	return o.ApplyT(func(v ToSecretResult) TsecretString1 { return v.ObjSecretString1 }).(TsecretString1Output)
}

func (o ToSecretResultOutput) ObjSecretString2() TsecretString2Output {
	return o.ApplyT(func(v ToSecretResult) TsecretString2 { return v.ObjSecretString2 }).(TsecretString2Output)
}

func (o ToSecretResultOutput) ObjSecretString3() TsecretString3Output {
	return o.ApplyT(func(v ToSecretResult) TsecretString3 { return v.ObjSecretString3 }).(TsecretString3Output)
}

func (o ToSecretResultOutput) ObjString1() Tstring1Output {
	return o.ApplyT(func(v ToSecretResult) Tstring1 { return v.ObjString1 }).(Tstring1Output)
}

func (o ToSecretResultOutput) ObjString2() Tstring2Output {
	return o.ApplyT(func(v ToSecretResult) Tstring2 { return v.ObjString2 }).(Tstring2Output)
}

func (o ToSecretResultOutput) ObjString3() Tstring3Output {
	return o.ApplyT(func(v ToSecretResult) Tstring3 { return v.ObjString3 }).(Tstring3Output)
}

func (o ToSecretResultOutput) SecretBool1() khulnasoft.BoolOutput {
	return o.ApplyT(func(v ToSecretResult) bool { return v.SecretBool1 }).(khulnasoft.BoolOutput)
}

func (o ToSecretResultOutput) SecretBool2() khulnasoft.BoolOutput {
	return o.ApplyT(func(v ToSecretResult) bool { return v.SecretBool2 }).(khulnasoft.BoolOutput)
}

func (o ToSecretResultOutput) SecretBool3() khulnasoft.BoolOutput {
	return o.ApplyT(func(v ToSecretResult) bool { return v.SecretBool3 }).(khulnasoft.BoolOutput)
}

func (o ToSecretResultOutput) SecretInt1() khulnasoft.IntOutput {
	return o.ApplyT(func(v ToSecretResult) int { return v.SecretInt1 }).(khulnasoft.IntOutput)
}

func (o ToSecretResultOutput) SecretInt2() khulnasoft.IntOutput {
	return o.ApplyT(func(v ToSecretResult) int { return v.SecretInt2 }).(khulnasoft.IntOutput)
}

func (o ToSecretResultOutput) SecretInt3() khulnasoft.IntOutput {
	return o.ApplyT(func(v ToSecretResult) int { return v.SecretInt3 }).(khulnasoft.IntOutput)
}

func (o ToSecretResultOutput) SecretNum1() khulnasoft.Float64Output {
	return o.ApplyT(func(v ToSecretResult) float64 { return v.SecretNum1 }).(khulnasoft.Float64Output)
}

func (o ToSecretResultOutput) SecretNum2() khulnasoft.Float64Output {
	return o.ApplyT(func(v ToSecretResult) float64 { return v.SecretNum2 }).(khulnasoft.Float64Output)
}

func (o ToSecretResultOutput) SecretNum3() khulnasoft.Float64Output {
	return o.ApplyT(func(v ToSecretResult) float64 { return v.SecretNum3 }).(khulnasoft.Float64Output)
}

func (o ToSecretResultOutput) SecretString1() khulnasoft.StringOutput {
	return o.ApplyT(func(v ToSecretResult) string { return v.SecretString1 }).(khulnasoft.StringOutput)
}

func (o ToSecretResultOutput) SecretString2() khulnasoft.StringOutput {
	return o.ApplyT(func(v ToSecretResult) string { return v.SecretString2 }).(khulnasoft.StringOutput)
}

func (o ToSecretResultOutput) SecretString3() khulnasoft.StringOutput {
	return o.ApplyT(func(v ToSecretResult) string { return v.SecretString3 }).(khulnasoft.StringOutput)
}

func (o ToSecretResultOutput) String1() khulnasoft.StringOutput {
	return o.ApplyT(func(v ToSecretResult) string { return v.String1 }).(khulnasoft.StringOutput)
}

func (o ToSecretResultOutput) String2() khulnasoft.StringOutput {
	return o.ApplyT(func(v ToSecretResult) string { return v.String2 }).(khulnasoft.StringOutput)
}

func (o ToSecretResultOutput) String3() khulnasoft.StringOutput {
	return o.ApplyT(func(v ToSecretResult) string { return v.String3 }).(khulnasoft.StringOutput)
}

func init() {
	khulnasoft.RegisterOutputType(ToSecretResultOutput{})
}
