// Code generated by khulnasoft-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"context"
	"reflect"

	"errors"
	"example.com/khulnasoft-config/sdk/go/v9/config/internal"
	"github.com/khulnasoft/sdk/go/khulnasoft"
)

type Provider struct {
	khulnasoft.ProviderResourceState

	Name              khulnasoft.StringOutput    `khulnasoft:"name"`
	PluginDownloadURL khulnasoft.StringPtrOutput `khulnasoft:"pluginDownloadURL"`
	Version           khulnasoft.StringOutput    `khulnasoft:"version"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *khulnasoft.Context,
	name string, args *ProviderArgs, opts ...khulnasoft.ResourceOption) (*Provider, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("khulnasoft:providers:config", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	Name              string  `khulnasoft:"name"`
	PluginDownloadURL *string `khulnasoft:"pluginDownloadURL"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	Name              khulnasoft.StringInput
	PluginDownloadURL khulnasoft.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	khulnasoft.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return khulnasoft.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *khulnasoft.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

func (o ProviderOutput) Name() khulnasoft.StringOutput {
	return o.ApplyT(func(v *Provider) khulnasoft.StringOutput { return v.Name }).(khulnasoft.StringOutput)
}

func (o ProviderOutput) PluginDownloadURL() khulnasoft.StringPtrOutput {
	return o.ApplyT(func(v *Provider) khulnasoft.StringPtrOutput { return v.PluginDownloadURL }).(khulnasoft.StringPtrOutput)
}

func (o ProviderOutput) Version() khulnasoft.StringOutput {
	return o.ApplyT(func(v *Provider) khulnasoft.StringOutput { return v.Version }).(khulnasoft.StringOutput)
}

func init() {
	khulnasoft.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	khulnasoft.RegisterOutputType(ProviderOutput{})
}
