# coding=utf-8
# *** WARNING: this file was generated by khulnasoft-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .hello_world import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "subpackage",
  "mod": "index",
  "fqn": "khulnasoft_subpackage",
  "classes": {
   "subpackage:index:HelloWorld": "HelloWorld"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "subpackage",
  "token": "khulnasoft:providers:subpackage",
  "fqn": "khulnasoft_subpackage",
  "class": "Provider"
 }
]
"""
)
