// *** WARNING: this file was generated by khulnasoft-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as khulnasoft from "@khulnasoft/khulnasoft";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface DataArgs {
    private: khulnasoft.Input<string>;
    public: khulnasoft.Input<string>;
}
