// Code generated by khulnasoft-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package secret

import (
	"context"
	"reflect"

	"example.com/khulnasoft-secret/sdk/go/v14/secret/internal"
	"github.com/khulnasoft/sdk/go/khulnasoft"
)

var _ = internal.GetEnvOrDefault

type Data struct {
	Private string `khulnasoft:"private"`
	Public  string `khulnasoft:"public"`
}

// DataInput is an input type that accepts DataArgs and DataOutput values.
// You can construct a concrete instance of `DataInput` via:
//
//	DataArgs{...}
type DataInput interface {
	khulnasoft.Input

	ToDataOutput() DataOutput
	ToDataOutputWithContext(context.Context) DataOutput
}

type DataArgs struct {
	Private khulnasoft.StringInput `khulnasoft:"private"`
	Public  khulnasoft.StringInput `khulnasoft:"public"`
}

func (DataArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Data)(nil)).Elem()
}

func (i DataArgs) ToDataOutput() DataOutput {
	return i.ToDataOutputWithContext(context.Background())
}

func (i DataArgs) ToDataOutputWithContext(ctx context.Context) DataOutput {
	return khulnasoft.ToOutputWithContext(ctx, i).(DataOutput)
}

type DataOutput struct{ *khulnasoft.OutputState }

func (DataOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Data)(nil)).Elem()
}

func (o DataOutput) ToDataOutput() DataOutput {
	return o
}

func (o DataOutput) ToDataOutputWithContext(ctx context.Context) DataOutput {
	return o
}

func (o DataOutput) Private() khulnasoft.StringOutput {
	return o.ApplyT(func(v Data) string { return v.Private }).(khulnasoft.StringOutput)
}

func (o DataOutput) Public() khulnasoft.StringOutput {
	return o.ApplyT(func(v Data) string { return v.Public }).(khulnasoft.StringOutput)
}

func init() {
	khulnasoft.RegisterInputType(reflect.TypeOf((*DataInput)(nil)).Elem(), DataArgs{})
	khulnasoft.RegisterOutputType(DataOutput{})
}
