# coding=utf-8
# *** WARNING: this file was generated by khulnasoft-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *
from .resource import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import khulnasoft_config.config as __config
    config = __config
else:
    config = _utilities.lazy_import('khulnasoft_config.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "config",
  "mod": "index",
  "fqn": "khulnasoft_config",
  "classes": {
   "config:index:Resource": "Resource"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "config",
  "token": "khulnasoft:providers:config",
  "fqn": "khulnasoft_config",
  "class": "Provider"
 }
]
"""
)
