// source: khulnasoft/errors.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var proto = { khulnasoftrpc: { codegen: { }, testing: { } } }, global = proto;

goog.exportSymbol('proto.khulnasoftrpc.ErrorCause', null, global);
goog.exportSymbol('proto.khulnasoftrpc.InputPropertiesError', null, global);
goog.exportSymbol('proto.khulnasoftrpc.InputPropertiesError.PropertyError', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.khulnasoftrpc.ErrorCause = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.khulnasoftrpc.ErrorCause, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.khulnasoftrpc.ErrorCause.displayName = 'proto.khulnasoftrpc.ErrorCause';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.khulnasoftrpc.InputPropertiesError = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.khulnasoftrpc.InputPropertiesError.repeatedFields_, null);
};
goog.inherits(proto.khulnasoftrpc.InputPropertiesError, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.khulnasoftrpc.InputPropertiesError.displayName = 'proto.khulnasoftrpc.InputPropertiesError';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.khulnasoftrpc.InputPropertiesError.PropertyError = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.khulnasoftrpc.InputPropertiesError.PropertyError, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.khulnasoftrpc.InputPropertiesError.PropertyError.displayName = 'proto.khulnasoftrpc.InputPropertiesError.PropertyError';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.khulnasoftrpc.ErrorCause.prototype.toObject = function(opt_includeInstance) {
  return proto.khulnasoftrpc.ErrorCause.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.khulnasoftrpc.ErrorCause} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.khulnasoftrpc.ErrorCause.toObject = function(includeInstance, msg) {
  var f, obj = {
    message: jspb.Message.getFieldWithDefault(msg, 1, ""),
    stacktrace: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.khulnasoftrpc.ErrorCause}
 */
proto.khulnasoftrpc.ErrorCause.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.khulnasoftrpc.ErrorCause;
  return proto.khulnasoftrpc.ErrorCause.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.khulnasoftrpc.ErrorCause} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.khulnasoftrpc.ErrorCause}
 */
proto.khulnasoftrpc.ErrorCause.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStacktrace(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.khulnasoftrpc.ErrorCause.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.khulnasoftrpc.ErrorCause.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.khulnasoftrpc.ErrorCause} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.khulnasoftrpc.ErrorCause.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStacktrace();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string message = 1;
 * @return {string}
 */
proto.khulnasoftrpc.ErrorCause.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.khulnasoftrpc.ErrorCause} returns this
 */
proto.khulnasoftrpc.ErrorCause.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string stackTrace = 2;
 * @return {string}
 */
proto.khulnasoftrpc.ErrorCause.prototype.getStacktrace = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.khulnasoftrpc.ErrorCause} returns this
 */
proto.khulnasoftrpc.ErrorCause.prototype.setStacktrace = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.khulnasoftrpc.InputPropertiesError.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.khulnasoftrpc.InputPropertiesError.prototype.toObject = function(opt_includeInstance) {
  return proto.khulnasoftrpc.InputPropertiesError.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.khulnasoftrpc.InputPropertiesError} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.khulnasoftrpc.InputPropertiesError.toObject = function(includeInstance, msg) {
  var f, obj = {
    errorsList: jspb.Message.toObjectList(msg.getErrorsList(),
    proto.khulnasoftrpc.InputPropertiesError.PropertyError.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.khulnasoftrpc.InputPropertiesError}
 */
proto.khulnasoftrpc.InputPropertiesError.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.khulnasoftrpc.InputPropertiesError;
  return proto.khulnasoftrpc.InputPropertiesError.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.khulnasoftrpc.InputPropertiesError} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.khulnasoftrpc.InputPropertiesError}
 */
proto.khulnasoftrpc.InputPropertiesError.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.khulnasoftrpc.InputPropertiesError.PropertyError;
      reader.readMessage(value,proto.khulnasoftrpc.InputPropertiesError.PropertyError.deserializeBinaryFromReader);
      msg.addErrors(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.khulnasoftrpc.InputPropertiesError.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.khulnasoftrpc.InputPropertiesError.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.khulnasoftrpc.InputPropertiesError} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.khulnasoftrpc.InputPropertiesError.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getErrorsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.khulnasoftrpc.InputPropertiesError.PropertyError.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.khulnasoftrpc.InputPropertiesError.PropertyError.prototype.toObject = function(opt_includeInstance) {
  return proto.khulnasoftrpc.InputPropertiesError.PropertyError.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.khulnasoftrpc.InputPropertiesError.PropertyError} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.khulnasoftrpc.InputPropertiesError.PropertyError.toObject = function(includeInstance, msg) {
  var f, obj = {
    propertyPath: jspb.Message.getFieldWithDefault(msg, 1, ""),
    reason: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.khulnasoftrpc.InputPropertiesError.PropertyError}
 */
proto.khulnasoftrpc.InputPropertiesError.PropertyError.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.khulnasoftrpc.InputPropertiesError.PropertyError;
  return proto.khulnasoftrpc.InputPropertiesError.PropertyError.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.khulnasoftrpc.InputPropertiesError.PropertyError} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.khulnasoftrpc.InputPropertiesError.PropertyError}
 */
proto.khulnasoftrpc.InputPropertiesError.PropertyError.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPropertyPath(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setReason(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.khulnasoftrpc.InputPropertiesError.PropertyError.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.khulnasoftrpc.InputPropertiesError.PropertyError.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.khulnasoftrpc.InputPropertiesError.PropertyError} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.khulnasoftrpc.InputPropertiesError.PropertyError.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPropertyPath();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getReason();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string property_path = 1;
 * @return {string}
 */
proto.khulnasoftrpc.InputPropertiesError.PropertyError.prototype.getPropertyPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.khulnasoftrpc.InputPropertiesError.PropertyError} returns this
 */
proto.khulnasoftrpc.InputPropertiesError.PropertyError.prototype.setPropertyPath = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string reason = 2;
 * @return {string}
 */
proto.khulnasoftrpc.InputPropertiesError.PropertyError.prototype.getReason = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.khulnasoftrpc.InputPropertiesError.PropertyError} returns this
 */
proto.khulnasoftrpc.InputPropertiesError.PropertyError.prototype.setReason = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated PropertyError errors = 1;
 * @return {!Array<!proto.khulnasoftrpc.InputPropertiesError.PropertyError>}
 */
proto.khulnasoftrpc.InputPropertiesError.prototype.getErrorsList = function() {
  return /** @type{!Array<!proto.khulnasoftrpc.InputPropertiesError.PropertyError>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.khulnasoftrpc.InputPropertiesError.PropertyError, 1));
};


/**
 * @param {!Array<!proto.khulnasoftrpc.InputPropertiesError.PropertyError>} value
 * @return {!proto.khulnasoftrpc.InputPropertiesError} returns this
*/
proto.khulnasoftrpc.InputPropertiesError.prototype.setErrorsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.khulnasoftrpc.InputPropertiesError.PropertyError=} opt_value
 * @param {number=} opt_index
 * @return {!proto.khulnasoftrpc.InputPropertiesError.PropertyError}
 */
proto.khulnasoftrpc.InputPropertiesError.prototype.addErrors = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.khulnasoftrpc.InputPropertiesError.PropertyError, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.khulnasoftrpc.InputPropertiesError} returns this
 */
proto.khulnasoftrpc.InputPropertiesError.prototype.clearErrorsList = function() {
  return this.setErrorsList([]);
};


goog.object.extend(exports, proto.khulnasoftrpc);
