// Code generated by khulnasoft-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package primitiveref

import (
	"context"
	"reflect"

	"example.com/khulnasoft-primitive-ref/sdk/go/v11/primitiveref/internal"
	"github.com/khulnasoft/sdk/go/khulnasoft"
)

var _ = internal.GetEnvOrDefault

type Data struct {
	BoolArray []bool            `khulnasoft:"boolArray"`
	Boolean   bool              `khulnasoft:"boolean"`
	Float     float64           `khulnasoft:"float"`
	Integer   int               `khulnasoft:"integer"`
	String    string            `khulnasoft:"string"`
	StringMap map[string]string `khulnasoft:"stringMap"`
}

// DataInput is an input type that accepts DataArgs and DataOutput values.
// You can construct a concrete instance of `DataInput` via:
//
//	DataArgs{...}
type DataInput interface {
	khulnasoft.Input

	ToDataOutput() DataOutput
	ToDataOutputWithContext(context.Context) DataOutput
}

type DataArgs struct {
	BoolArray khulnasoft.BoolArrayInput `khulnasoft:"boolArray"`
	Boolean   khulnasoft.BoolInput      `khulnasoft:"boolean"`
	Float     khulnasoft.Float64Input   `khulnasoft:"float"`
	Integer   khulnasoft.IntInput       `khulnasoft:"integer"`
	String    khulnasoft.StringInput    `khulnasoft:"string"`
	StringMap khulnasoft.StringMapInput `khulnasoft:"stringMap"`
}

func (DataArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Data)(nil)).Elem()
}

func (i DataArgs) ToDataOutput() DataOutput {
	return i.ToDataOutputWithContext(context.Background())
}

func (i DataArgs) ToDataOutputWithContext(ctx context.Context) DataOutput {
	return khulnasoft.ToOutputWithContext(ctx, i).(DataOutput)
}

type DataOutput struct{ *khulnasoft.OutputState }

func (DataOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Data)(nil)).Elem()
}

func (o DataOutput) ToDataOutput() DataOutput {
	return o
}

func (o DataOutput) ToDataOutputWithContext(ctx context.Context) DataOutput {
	return o
}

func (o DataOutput) BoolArray() khulnasoft.BoolArrayOutput {
	return o.ApplyT(func(v Data) []bool { return v.BoolArray }).(khulnasoft.BoolArrayOutput)
}

func (o DataOutput) Boolean() khulnasoft.BoolOutput {
	return o.ApplyT(func(v Data) bool { return v.Boolean }).(khulnasoft.BoolOutput)
}

func (o DataOutput) Float() khulnasoft.Float64Output {
	return o.ApplyT(func(v Data) float64 { return v.Float }).(khulnasoft.Float64Output)
}

func (o DataOutput) Integer() khulnasoft.IntOutput {
	return o.ApplyT(func(v Data) int { return v.Integer }).(khulnasoft.IntOutput)
}

func (o DataOutput) String() khulnasoft.StringOutput {
	return o.ApplyT(func(v Data) string { return v.String }).(khulnasoft.StringOutput)
}

func (o DataOutput) StringMap() khulnasoft.StringMapOutput {
	return o.ApplyT(func(v Data) map[string]string { return v.StringMap }).(khulnasoft.StringMapOutput)
}

func init() {
	khulnasoft.RegisterInputType(reflect.TypeOf((*DataInput)(nil)).Elem(), DataArgs{})
	khulnasoft.RegisterOutputType(DataOutput{})
}
