# coding=utf-8
# *** WARNING: this file was generated by khulnasoft-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .my_invoke import *
from .provider import *
from .secret_invoke import *
from .string_resource import *
from .unit import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "simple-invoke",
  "mod": "index",
  "fqn": "khulnasoft_simple_invoke",
  "classes": {
   "simple-invoke:index:StringResource": "StringResource"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "simple-invoke",
  "token": "khulnasoft:providers:simple-invoke",
  "fqn": "khulnasoft_simple_invoke",
  "class": "Provider"
 }
]
"""
)
